version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: gsd-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gsd
      POSTGRES_PASSWORD: gsd_dev_password
      POSTGRES_DB: gsd_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U gsd']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gsd-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@gsd.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    profiles:
      - tools

volumes:
  postgres_data:
